# Netlify Build Configuration
# This file forces Node.js builds and prevents Docker detection

[build]
  # CRITICAL: Force Node.js build environment
  command = "cd mitraverify-frontend && npm ci && npm run build"
  publish = "mitraverify-frontend/out"
  base = "."
  
[build.environment]
  # Force specific Node.js version
  NODE_VERSION = "18.17.0"
  # Disable all non-Node.js build systems
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "false"
  # Explicitly disable Docker
  DOCKER_ENABLED = "false"
  BUILDPACK_URL = "https://github.com/heroku/heroku-buildpack-nodejs"
  # Force npm
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "cd mitraverify-frontend && npm run dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Context-specific builds (all identical to force consistency)
[context.production]
  command = "cd mitraverify-frontend && npm ci && npm run build"
  publish = "mitraverify-frontend/out"

[context.deploy-preview]
  command = "cd mitraverify-frontend && npm ci && npm run build"
  publish = "mitraverify-frontend/out"

[context.branch-deploy]
  command = "cd mitraverify-frontend && npm ci && npm run build"
  publish = "mitraverify-frontend/out"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[plugins]]
  # Essential Next.js plugin for Netlify
  package = "@netlify/plugin-nextjs"

[dev]
  # Local development configuration
  command = "npm run dev"
  port = 3000
  publish = "out"

[[redirects]]
  # Handle Next.js dynamic routes and SPA routing
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  # API proxy for development (optional)
  from = "/api/*"
  to = "http://localhost:8000/api/:splat"
  status = 200
  force = false
  conditions = {Country = ["dev"]}

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific settings
[context.production]
  command = "npm ci && npm run build"
  publish = "out"

[context.deploy-preview]
  command = "npm ci && npm run build"
  publish = "out"

[context.branch-deploy]
  command = "npm ci && npm run build"
  publish = "out"