[build]
  # Build configuration for Netlify
  publish = ".next"
  command = "npm run build"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # NPM configuration
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  # Essential Next.js plugin for Netlify
  package = "@netlify/plugin-nextjs"

[dev]
  # Local development configuration
  command = "npm run dev"
  port = 3000
  publish = ".next"

[[redirects]]
  # Handle Next.js dynamic routes
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  # API proxy for development (optional)
  from = "/api/*"
  to = "http://localhost:8000/api/:splat"
  status = 200
  force = false
  condition = "Country=dev"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific settings
[context.production]
  command = "npm run build"
  publish = ".next"

[context.deploy-preview]
  command = "npm run build"
  publish = ".next"

[context.branch-deploy]
  command = "npm run build"
  publish = ".next"