name: Deploy to Netlify

on:
  push:
    branches: [main, develop]
    paths:
      - 'mitraverify-frontend/**'
      - '.github/workflows/netlify-deploy.yml'
  pull_request:
    branches: [main]
    paths:
      - 'mitraverify-frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./mitraverify-frontend
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './mitraverify-frontend/package-lock.json'

    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    - name: Run type check
      run: npm run type-check

    - name: Run linting
      run: npm run lint

    - name: Build application
      run: npm run build
      env:
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        NEXT_PUBLIC_APP_NAME: MitraVerify
        SITE_URL: ${{ secrets.SITE_URL }}

    - name: Deploy to Netlify (Production)
      if: github.ref == 'refs/heads/main'
      uses: netlify/actions/cli@master
      with:
        args: deploy --prod --dir=mitraverify-frontend/out
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    - name: Deploy to Netlify (Preview)
      if: github.ref != 'refs/heads/main'
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=mitraverify-frontend/out
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    - name: Comment PR with preview URL
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const output = `
          ## 🚀 Deployment Preview
          
          Your changes have been deployed to Netlify!
          
          - **Preview URL**: Available in Netlify dashboard
          - **Build Time**: ${new Date().toISOString()}
          - **Commit**: ${context.sha.substring(0, 7)}
          
          ### What's included:
          - ✅ Frontend application
          - ✅ Static optimization
          - ✅ SEO configuration
          - ✅ Performance optimizations
          
          Please test the preview before merging.
          `;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          });